apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-disk
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: diskplugin.csi.alibabacloud.com
parameters:
  type: available
  volumeSizeAutoAvailable: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
